<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>HotelManagement.Domain</RootNamespace>
    <AssemblyName>HotelManagement.Domain</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Events\**" />
    <EmbeddedResource Remove="Events\**" />
    <None Remove="Events\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
  </ItemGroup>

</Project>
